app/models.py
from . import db


class ChartData(db.Model):
    __tablename__ = 'chartdata'

    EmpID = db.Column(db.Integer, primary_key=True)
    EmpName = db.Column(db.String(255), nullable=False)
    UserName = db.Column(db.String(255), nullable=False)
    Designation = db.Column(db.String(255), nullable=False)
    BusinessUnit = db.Column(db.String(255), nullable=False)
    Reportee = db.Column(db.String(255), nullable=True)
    Reporter = db.Column(db.String(255), nullable=True)

    def to_dict(self):
        return {
            'EmpID': self.EmpID,
            'EmpName': self.EmpName,
            'UserName': self.UserName,
            'Designation': self.Designation,
            'BusinessUnit': self.BusinessUnit,
            'Reportee': self.Reportee,
            'Reporter': self.Reporter
        }

app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()


def create_app():
    app = Flask(__name__)

    # Database configuration
    app.config['SQLALCHEMY_DATABASE_URI'] = 'mysql+pymysql://root:Hema098@localhost/orgdb'
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

    db.init_app(app)

    with app.app_context():
        from .controllers import register_blueprints
        register_blueprints(app)

        # Import the models
        from . import models
        db.create_all()

    return app

app/controllers.py
from flask import render_template, Blueprint
from .services import get_team_members

main_bp = Blueprint('main', __name__)

@main_bp.route('/')
def index():
    team_members = [member.to_dict() for member in get_team_members()]
    return render_template('index.html', team_members=team_members)

@main_bp.route('/index1')
def index1():
    team_members = [member.to_dict() for member in get_team_members()]
    return render_template('index1.html', team_members=team_members)

@main_bp.route('/index2')
def index2():
    team_members = [member.to_dict() for member in get_team_members()]
    return render_template('index2.html', team_members=team_members)

def register_blueprints(app):
    app.register_blueprint(main_bp)

app/main/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_bcrypt import Bcrypt

from .config import config_by_name

db = SQLAlchemy()
flask_bcrypt = Bcrypt()


def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config_by_name[config_name])
    db.init_app(app)
    flask_bcrypt.init_app(app)

    return app

app/main/config/__init__.py
def basedir():
    return None

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
    {% block head %}{% endblock %}
</head>
<body>
    {% block body %}{% endblock %}
</body>
</html>

app/templates/index.html
<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}" />
    <title>TS</title>
</head>
<body>
<div class="v1_2">
    <div class="v1_6" style="background-image: url('{{ url_for('static', filename='bg.jpg') }}')">
        <div class="v5">
            <img src="{{ url_for('static', filename='hcl.jpg') }}">
        </div>
    </div>
    <div class="v1_7"></div>
    <div class="v1_8"></div>
    <div class="v1_9"></div>
    {% for member in team_members %}
    {% if member.EmpID==109 %}
    <span class="v2_10">
        <h1>{{ member['EmpName'] }}</h1>
        <h4>{{ member['Designation'] }}</h4>
    </span>
    {% endif %}
    {% endfor %}
    <div class="v1_13"></div>
    <a href="{{ url_for('main.index2') }}">
        <div class="v2_2"></div>
        <span class="v2_6">
            <h2>Michael Smith</h2>
            <h5>CHAIRMAN & CHIEF STRATEGY OFFICER Executive</h5>
        </span>
    </a>
    <div class="v2_5"></div>
    <div class="v2_8" style="height:45px"></div>
    <div class="v2_200"></div>
    <a href="{{ url_for('main.index1') }}">
        <span class="v2_600">
            <h2>Jessica Brown</h2>
            <h5>GENERAL MANAGER || Business Management</h5>
        </span>
    </a>
    <div class="v2_500"></div>
    <div class="v2_8" style="height:55px; top:725px"></div>
    <div class="v2_2" style="top:780px"></div>
    <span class="v2_6" style="top:790px">
        <h2>Daniel Garcia</h2>
        <h5>TECHNICAL SPECIALIST || Technical</h5>
    </span>
    <div class="v2_5" style="top:790px"></div>
    <div class="v2_8" style="height:50px; top:885px"></div>
    <div class="v2_7" style="top:930px"></div>
    <div class="v2_13" style="top:977px"></div>
    <span class="v2_23" style="top:972px">
        <h3>Ashley Wilson</h3>
        <h5>LEAD CONSULTANT</h5>
    </span>
    <div class="v2_16" style="top:979px"></div>
    <div class="v2_12" style="top:1079px"></div>
    <span class="v2_25" style="top:1072px">
        <h3>Matthew Lee</h3>
        <h5>Technical Lead</h5>
    </span>
    <div class="v2_21" style="top:1079px"></div>
    <div class="v2_14" style="top:977px"></div>
    <span class="v2_24" style="top:972px">
        <h3>Lauren Martinez</h3>
        <h5>Senior Software Engineer</h5>
    </span>
    <div class="v2_20" style="top:979px"></div>
    <div class="v2_11" style="top:1079px"></div>
    <span class="v2_26" style="top:1070px">
        <h3>Nicholas Brown</h3>
        <h5>Senior Test Engineer</h5>
    </span>
    <div class="v2_22" style="top:1079px"></div>
</div>
</body>
</html>

app/templates/index1.html
<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}" />
    <title>GM</title>
</head>
<body>
<div class="v1_2">
    <div class="v1_6" style="background-image: url('{{ url_for('static', filename='bg.jpg') }}')">
        <div class="v5">
            <img src="{{ url_for('static', filename='hcl.jpg') }}">
        </div>
    </div>
    <div class="v1_7"></div>
    <div class="v1_8"></div>
    <div class="v1_9"></div>
    {% for member in team_members %}
    {% if member.EmpID==105 %}
    <span class="v2_10"><h1>{{ member['EmpName'] }}</h1><h4>{{ member['Designation'] }}</h4></span>
    {% endif %}
    {% endfor %}
    <div class="v1_13"></div>
    <a href="{{ url_for('main.index2') }}">
        <div class="v2_2"></div>
        <span class="v2_6"><h2>Michael Smith</h2><h5>CHAIRMAN & CHIEF STRATEGY OFFICER Executive</h5></span>
    </a>
    <div class="v2_5"></div>
    <div class="v2_8" style="height:45px"></div>
    <div class="v2_200"></div>
    <span class="v2_600"><h2>Jessica Brown</h2><h5>GENERAL MANAGER || Business Management</h5></span>
    <div class="v2_500"></div>
    <div class="v2_8" style="height:55px; top:725px"></div>
    <div class="v2_7" style="top:780px"></div>
    <div class="v2_13" style="top:827px"></div>
    <span class="v2_23" style="top:822px"><h3>Ashley Wilson</h3><h5>TECHNICAL MANAGER</h5></span>
    <div class="v2_16" style="top:829px"></div>
    <div class="v2_12" style="top:929px"></div>
    <a href="{{ url_for('main.index') }}">
        <span class="v2_25" style="top:922px"><h3>Daniel Garcia</h3><h5>TECHNICAL SPECIALIST</h5></span>
    </a>
    <div class="v2_21" style="top:929px"></div>
    <div class="v2_14" style="top:827px"></div>
    <span class="v2_24" style="top:822px"><h3>Samantha Thomas</h3><h5>SENIOR TECHNICAL LEAD</h5></span>
    <div class="v2_20" style="top:829px"></div>
    <div class="v2_11" style="top:929px"></div>
    <span class="v2_26" style="top:920px"><h3>Joshua Rodriguez</h3><h5>SENIOR CONSULTANT</h5></span>
    <div class="v2_22" style="top:929px"></div>
</div>
</body>
</html>

app/templates/index2.html
<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}" />
    <title>CEO</title>
</head>
<body>
<div class="v1_2">
    <div class="v1_6" style="background-image: url('{{ url_for('static', filename='bg.jpg') }}')">
        <div class="v5">
            <img src="{{ url_for('static', filename='hcl.jpg') }}">
        </div>
    </div>
    <div class="v1_7"></div>
    <div class="v1_8"></div>
    <div class="v1_9"></div>
    {% for member in team_members %}
    {% if member.EmpID==101 %}
    <span class="v2_10"><h1>{{ member['EmpName'] }}</h1><h4>{{ member['Designation'] }}</h4></span>
    {% endif %}
    {% endfor %}
    <div class="v1_13"></div>
    <div class="v2_2"></div>
    <span class="v2_6"><h2>Michael Smith</h2><h5>CHAIRMAN & CHIEF STRATEGY OFFICER Executive</h5></span>
    <div class="v2_5"></div>
    <div class="v2_7"></div>
    <div class="v2_13"></div>
    <span class="v2_23"><h3>Sarah Johnson</h3><h5>CEO & MANAGING DIRECTOR</h5></span>
    <div class="v2_16"></div>
    <div class="v2_12"></div>
    <span class="v2_25"><h3>David Martinez</h3><h5>SENIOR VICE PRESIDENT</h5></span>
    <div class="v2_21"></div>
    <div class="v2_14"></div>
    <span class="v2_24"><h3>Emily Davis</h3><h5>CORPORATE VICE PRESIDENT</h5></span>
    <div class="v2_20"></div>
    <div class="v2_8"></div>
    <a href="{{ url_for('main.index1') }}">
        <div class="v2_11"></div>
        <span class="v2_26"><h3>Jessica Brown</h3><h5>GENERAL MANAGER</h5></span>
    </a>
    <div class="v2_22"></div>
</div>
</body>
</html>

app/templates/update.html
{% extends 'base.html' %}

{% block head %}
<title>Task Master</title>
{% endblock %}

{% block body %}
<div class="content">
    <h1 style="text-align: center">Update Task</h1>

    <div class="form">
        <form action="/update/{{task.id}}" method="POST">
            <input type="text" name="content" id="content" value="{{task.content}}">
            <input type="submit" value="Update">
        </form>
    </div>
</div>
{% endblock %}